### PR TITLE
fix: Wait for Stacks Blocks in Integration test

### LINKED ISSUE #73: Tests are flaking
**Describe the bug**
Tests are flaking. Seems to be due to the fact that the tests `sleep`, rather than wait for a specified period of blocks.

E.g., `l1_integration_test` can sometimes fail on

```
    assert!(
        account.nonce >= 2,
        "Miner should have produced at least 2 coinbase transactions"
    );
```

The reason seems to be that we don't always wait for 2 L2 stacks blocks.

**Steps To Reproduce**
Run test many times.

**Expected behavior**
Test should always pass.

### PR DESCRIPTION
**Pull request by gregorycoppola**
### Description

Adds `wait_for_next_stacks_block` to wait for the height of the *stacks* tip to increment.

Looks like `l1_integration_test` is passing reliably now.

### Applicable issues
- fixes #73

### Checklist
- [x] Test coverage for new or modified code paths

### CODE REVIEW

File: src/chainstate/burn/db/sortdb.rs [hunk 1]
```diff
@@ -2413,6 +2413,16 @@ impl SortitionDB {
...
+    /// Like `get_canonical_sortition_tip` but returns whole BlockSnapshot.
+    pub fn get_canonical_sortition_tip_snapshot(
+        conn: &Connection,
+    ) -> Result<Option<BlockSnapshot>, db_error> {
+        let qry = "SELECT * FROM snapshots WHERE pox_valid = 1 ORDER BY block_height DESC, burn_header_hash ASC LIMIT 1";
+        match query_row(conn, qry, NO_PARAMS) {
+            Ok(opt) => Ok(opt),
+            Err(e) => Err(db_error::from(e)),
+        }
+    }
```
Comment (kantai) [inline src/chainstate/burn/db/sortdb.rs:2425]: Does `get_canonical_burn_chain_tip()` not work? It returns `Result<BlockSnapshot, db_error>`

File: testnet/stacks-node/src/tests/l1_observer_test.rs [hunk 2]
```diff
@@ -218,6 +258,16 @@ fn l1_integration_test() {
...
+    let sortition_db = {
+        let burnchain = Burnchain::new(
+            &config.get_burn_db_path(),
+            &config.burnchain.chain,
+            &config.burnchain.mode,
+        )
+        .unwrap();
+        SortitionDB::open(&burnchain.get_db_path(), true).unwrap()
+    };
+
```
Comment (kantai) [inline testnet/stacks-node/src/tests/l1_observer_test.rs:270]: I think you can move the instantiation of `burndb` at ~line 324 up here. The method `open_db()` returns a pair of `SortitionDB` and the `BurnchainDB`, so this could kind of be deduped by just using the currently dropped element of that return pair.

File: src/chainstate/burn/db/sortdb.rs (hunk 1 above)
Comment (gregorycoppola) [reply src/chainstate/burn/db/sortdb.rs]: oh yeah, this works.. it panics if it finds no block but so far works.

File: testnet/stacks-node/src/tests/l1_observer_test.rs (hunk 2 above)
Comment (gregorycoppola) [reply testnet/stacks-node/src/tests/l1_observer_test.rs]: true

File: testnet/stacks-node/src/tests/l1_observer_test.rs [hunk 3]
```diff
@@ -218,6 +255,14 @@ fn l1_integration_test() {
     // Give the run loop time to start.
     thread::sleep(Duration::from_millis(2_000));
 
+    let burnchain = Burnchain::new(
+        &config.get_burn_db_path(),
+        &config.burnchain.chain,
+        &config.burnchain.mode,
+    )
+    .unwrap();
+    let sortition_db = SortitionDB::open(&burnchain.get_db_path(), true).unwrap();
```
Comment (kantai) [inline testnet/stacks-node/src/tests/l1_observer_test.rs:264]:
```suggestion
    let (sortition_db, burndb) = burnchain.open_db(true).unwrap();
```

And then you can delete line 319 as well.

**Review by kantai — APPROVED** [review]
LGTM, just one last suggestion.

**Comment by gregorycoppola** [comment]
Thanks for the reviews!
